/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.pMDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pMDSL.Model#getEntities <em>Entities</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pMDSL.Model#getRelations <em>Relations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pMDSL.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getModel_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pMDSL.Relation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getModel_Relations()
   * @model containment="true"
   * @generated
   */
  EList<Relation> getRelations();

} // Model
