/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.pMDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pMDSL.Relation#getRelationsList <em>Relations List</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends EObject
{
  /**
   * Returns the value of the '<em><b>Relations List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pMDSL.RelationElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations List</em>' containment reference list.
   * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getRelation_RelationsList()
   * @model containment="true"
   * @generated
   */
  EList<RelationElement> getRelationsList();

} // Relation
