/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.pMDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pMDSL.Type#getEntity <em>Entity</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pMDSL.Type#getPrimitive <em>Primitive</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getType_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pMDSL.Type#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Primitive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primitive</em>' attribute.
   * @see #setPrimitive(String)
   * @see org.xtext.example.mydsl.pMDSL.PMDSLPackage#getType_Primitive()
   * @model
   * @generated
   */
  String getPrimitive();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pMDSL.Type#getPrimitive <em>Primitive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primitive</em>' attribute.
   * @see #getPrimitive()
   * @generated
   */
  void setPrimitive(String value);

} // Type
