/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.productmanagement.ui.internal.ProductmanagementActivator;

public class PMDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProductmanagementActivator.getInstance().getInjector("org.xtext.example.mydsl.PMDSL");
	}

}
