/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.productmanagement.ui.internal.ProductmanagementActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PMDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProductmanagementActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProductmanagementActivator activator = ProductmanagementActivator.getInstance();
		return activator != null ? activator.getInjector(ProductmanagementActivator.ORG_XTEXT_EXAMPLE_MYDSL_PMDSL) : null;
	}

}
