/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PMDSLUiModule extends AbstractPMDSLUiModule {

	public PMDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
