grammar org.xtext.example.mydsl.PMDSL with org.eclipse.xtext.common.Terminals

generate pMDSL "http://www.xtext.org/example/mydsl/PMDSL"

Model:
    entities+=Entity*;

Entity:
    'component' name=ID '{'
        attributes+=Attribute*
    '}';

Attribute:
    'attribute' name=ID 'as' type=Type;
    
Type:
	entity=[Entity] | primitive=PrimitiveType;
	
PrimitiveType:
	'number' | 'string' | 'boolean' | 'date' | 'number[]' | 'string[]' | 'boolean[]' | 'date[]';
