/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PMDSLStandaloneSetup extends PMDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new PMDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
